In [1]:
pip install numpy

In [2]:
# Create a NumPy array:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

print(np.__version__)

1.25.2


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [6]:
# Create a 0-D array with value 42
import numpy as np

arr = np.array(42)
print(arr)

42


In [7]:
# Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np

arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print("N.o of Dimensions:",arr.ndim)

[[[[[1 2 3 4 5]]]]]
N.o of Dimensions: 5


In [11]:
# Get the first element from the following array:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [12]:
# Get the second element from the following array:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [13]:
# Access the element on the first row, second column:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element on 1st row :",arr[0,1])

2nd element on 1st row : 2


In [14]:
# Access the element on the 2nd row, 5th column:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("5th element on 2nd row :",arr[1,4])

5th element on 2nd row : 10


In [15]:
# Access the third element of the second array of the first array:
import numpy as np

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0,1,2])

6


In [16]:
# Print the last element from the 2nd dim:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Last element from 2nd dim: ",arr[1,-1])

Last element from 2nd dim:  10


In [17]:
# Slice elements from index 1 to index 5 from the following array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

[2 3 4 5]


In [18]:
# Slice elements from index 4 to the end of the array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[4:])

[5 6 7 8]


In [19]:
# Slice elements from the beginning to index 4 (not included):
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[:4])

[1 2 3 4]


In [20]:
# Slice from the index 3 from the end to index 1 from the end:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[-3:-1])

[6 7]


In [21]:
# Return every other element from index 1 to index 5:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5:2])

[2 4]


In [22]:
# Return every other element from the entire array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr[::2])

[1 3 5 7]


In [23]:
# From the second element, slice elements from index 1 to index 4 (not included):
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [24]:
# From both elements, return index 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [25]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [26]:
# Get the data type of an array object:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [27]:
# Get the data type of an array containing strings:
import numpy as np

arr = np.array(["apple","banana","cherry"])
print(arr.dtype)

<U6


In [28]:
# Create an array with data type string:
import numpy as np

arr = np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [29]:
# Create an array with data type 4 bytes integer:
import numpy as np

arr = np.array([1,2,3,4,5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [30]:
# Change data type from float to integer by using 'i' as parameter value:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [31]:
# Change data type from float to integer by using int as parameter value:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [32]:
# Change data type from integer to boolean:
import numpy as np

arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [33]:
# Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 50
print(arr)
print(x)

[50  2  3  4  5]
[1 2 3 4 5]


In [34]:
# Make a view, change the original array, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] =  50
print(arr)
print(x)

[50  2  3  4  5]
[50  2  3  4  5]


In [35]:
# Make a view, change the view, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] =  30
print(arr)
print(x)

[30  2  3  4  5]
[30  2  3  4  5]


In [36]:
# Print the value of the base attribute to check if an array owns it's data or not:
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [37]:
# Print the shape of a 2-D array:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [38]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("Shape of Array:",arr.shape)

[[[[[1 2 3 4]]]]]
Shape of Array: (1, 1, 1, 1, 4)


In [39]:
# Print the shape of a 2-D array:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [40]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("Shape of Array:",arr.shape)

[[[[[1 2 3 4]]]]]
Shape of Array: (1, 1, 1, 1, 4)


In [41]:
# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
# Convert the array into a 1D array:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [44]:
# Iterate on the elements of the following 1-D array:
import numpy as np

arr = np.array([1,2,3,4,5])
for x in arr:
  print(x)

1
2
3
4
5


In [45]:
# Iterate on the elements of the following 2-D array:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [46]:
# Iterate on each scalar element of the 2-D array:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [47]:
# Iterate on the elements of the following 3-D array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [48]:
# Iterate down to the scalars:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [49]:
# Iterate through the following 3-D array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
# Iterate through the array as a string:
import numpy as np

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [51]:
# Iterate through every scalar element of the 2D array skipping 1 element:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [52]:
# Enumerate on following 1D arrays elements:
import numpy as np

arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [53]:
# Find the indexes where the value is 4:
import numpy as np

arr = np.array([1,2,3,4,2,4,9,4,5,7])
x = np.where(arr == 4)
print(x)

(array([3, 5, 7]),)


In [54]:
# Find the indexes where the value 7 should be inserted:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [55]:
# Find the indexes where the values 2, 4, and 6 should be inserted:
import numpy as np

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


In [56]:
# Sort the array:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [57]:
# Sort a 2-D array:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
